# settings.yml 1.0.9.4
# this file: CC BY-ND 4.0
# zer0Kerbal
# created 01 Jan 2022
# updated 03 Jun 2022
# These settings are synced to GitHub by https://probot.github.io/apps/settings/
# See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

repository:
  # The name of the repository. Changing this will rename the repository
  name: Taerobee 

  # A short description of the repository that will show up on GitHub
  description: This Mod adds some early rocket engines, such as Aerobee and X-4 (V-2 sounding rocket) for Kerbal Space Program.

  # A URL with more information about the repository
  homepage: http://forum.kerbalspaceprogram.com/index.php?/topic/205846-*/
  
  # A comma-separated list of topics to set on the repository
  topics: rockets,wernher,werhners-old-stuff,kerbal,kerbalspaceprogram,ksp,ksp-mods,ksp-parts,kerbal-space,kerbal-space-program,kerbal-mods,zedk,baele
  
# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug 🐛
    color: CC0000
    description: An issue with the system. Something isn't working... KSC... we have an error code

  - name: "help wanted"
    color: 008672
    description: "assistance, help, input solicited"

  - name: discussion
    color: 6495ED
    description: "duplicated issue - it happens"

  - name: duplicate
    color: FFFFF0
    description: "duplicated issue - it happens"

  - name: FAQ
    color: 78A1A5
    description: "Frequently Asked Question"

  - name: "semantic: adoption"
    # include the old name to rename an existing label
    oldname: adoption
    color: BADA55
    description: relating to adoption

  - name: "semantic: release"
    color: 00FF00
    description: release

  - name: "semantic: prerelease"
    color: 00FF00
    description: prerelase

  - name: "semantic: beta"
    color: 00FF00
    description: beta

  - name: "semantic: alpha"
    color: 00FF00
    description: alpha

  - name: "issue: text"
    color: FBCA04
    description: issue type

  - name: "issue: compatibility/patch"
    color: CC0DEB
    description: issue type

  - name: "issue: model"
    color: FBCA04
    description: issue type

  - name: "issue: texture"
    color: FBCA04
    description: issue type

  - name: "issue: sound"
    color: FBCA04
    description: issue type

  - name: "issue: config"
    color: FBCA04
    description: issue type

  - name: "issue: code"
    color: FBCA04
    description: issue type

  - name: "issue: documentation"
    color: FBCA04
    description: issue type

  - name: "issue: relationship"
    color: FBCA04
    description: issue type

  - name: "issue: license"
    color: FBCA04
    description: having to do with license/licensing

  - name: "issue: image"
    color: FBCA04
    description: deals with images and imgbot

  - name: "issue: install"
    color: FBCA04
    description: issue type

  - name: "issue: other"
    color: FBCA04
    description: issue type

  - name: "issue: external"
    color: FBCA04
    description: issue originates from external sources

  - name: "type: localization"
    oldname: localization
    # include the old name to rename an existing label
    color: FFFFF0
    description: related to localization and translations

  - name: "type: infrastructure"
    color: ffdda8
    description: improvements or additions to project infrastructure

  - name: "type: automation"
    color: fbca04
    description: issues for automation actions

  - name: "type: fix"
    color: 91ca55
    description: Iterations on existing features or infrastructure.

  - name: "type: testing"
    color: fbca04
    description: Related to testing.

  - name: "type: chore"
    color: fef2c0
    description: Converting measurements, reorganizing folder structure, and other necessary (but less impactful) tasks.

  - name: "type: discussion"
    oldname: discussion
    color: d4c5f9
    description: Questions, queries, posers, proposals and info that requires discussion.

  - name: "type: docs"
    color: fef2c0
    description: Related to documentation and information.

  - name: "type: pages"
    color: fef2c0
    description: Related to GitHub pages documentation and information.

  - name: "type: enhancement"
    oldname: "Mod-enhancement"
    # include the old name to rename an existing label
    color: 5ebeff
    description: Requested functionality, features, pages, workflows, endpoints, etc.

  - name: "type: feature"
    oldname: "Mod-feature"
    # include the old name to rename an existing label
    description: Brand new functionality, features, pages, workflows, endpoints, etc.

  - name: "type: request"
    oldname: "Mod-request"
    # include the old name to rename an existing label
    color: 5ebeff
    description: Requested functionality, features, pages, workflows, endpoints, etc.

  - name: "type: archive"
    color: FFFFF0
    description: archive

  - name: "type: upstream"
    oldname: "upstream"
    # include the old name to rename an existing label
    color: FFFFF0
    description: upstream or side stream

  - name: "type: pull request"
    oldname: "pull request"
    color: FFFFF0
    description: upstream or side stream

  - name: "work: choatic"
    color: FBCA04
    description: The situation is chaotic, novel practices used.

  - name: "work: complex"
    color: d4c5f9
    description: The situation is complex, emergent practices used.

  - name: "work: complicated"
    color: ffb8c6
    description: The situation is complicated, good practices used.

  - name: "work: obvious"
    color: 91ca55
    description: The situation is obvious, best practices used.

  - name: "state: approved"
    color: 91ca55
    description: Approved to proceed.

  - name: "state: blocked"
    color: d73a4a
    description: Something is blocking action.

  - name: "state: pending"
    color: fbca04
    description: Taking action, but need a few things to happen first. A feature that needs dependencies merged, or a bug that needs further data.

  - name: "state: inactive"
    color: e6e6e6
    description: No action needed or possible. The issue is either fixed, addressed better by other issues, or just out of product scope.

  - name: "state: planning"
    color: FFFF00
    description:

  - name: "state: won't fix"
    color: e6e6e6
    description: No action will be taken at this time

# Milestones: define milestones for Issues and Pull Requests
# milestones:
#   - title: 1.4.2.0-releasae
#     description: progress toward 1.4.2.0-releasae
#     state: open

#   - title: Localization - Master
#     description: progress toward total localization
#     state: open
    
#  - title: Localization - Code
#    description: progress toward CODE localization (only for add-ons - plugins - etc)
#    state: open
#    
#  - title: Localization - English (United States) <en-us.cfg>
#    description: progress toward English (United States) <en-us.cfg> localization
#    state: open
#    
#  - title: Localization - German (Deutsch) <de.cfg>
#    description: progress toward German (Deutsch) <de.cfg> localization
#    state: open
#    
#  - title: Localization - Spanish (Español) <es-es.cfg>
#    description: progress toward Spanish (Español) <es-es.cfg> localization
#    state: open
#    
#  - title: Localization - Mexican Spanish  (Mexicano) <es-mx.cfg>
#    description: progress toward Mexican Spanish (Mexicano) <es-mx.cfg> localization
#    state: open
#    
#  - title: Localization - French (Français) <fr-fr.cfg>
#    description: progress toward French (Français) <fr-fr.cfg> localization
#    state: open
#    
#  - title: Localization - Italian (Italiano) <it-it.cfg>
#    description: progress toward Italian (Italiano) <it-it.cfg> localization
#    state: open
#    
#  - title: Localization - Japanese(日本語) <ja.cfg>
#    description: progress toward Japanese(日本語) <ja.cfg> localization
#    state: open
#    
#  - title: Localization - Korean (한국어) <ko.cfg>
#    description: progress toward Korean (한국어) <ko.cfg> localization
#    state: open
#    
#  - title: Localization - Dutch (Nederlands) <nl-nl.cfg>
#    description: progress toward Dutch (Nederlands) <nl-nl.cfg> localization
#    state: open
#    
#  - title: Localization - Norwegian (Norsk) <no-no.cfg>
#    description: progress toward Norwegian (Norsk) <no-no.cfg> localization
#    state: open
#    
#  - title: Localization - Polish (Polski) <pl.cfg>
#    description: progress toward Polish (Polski) <pl.cfg> localization
#    state: open
#    
#  - title: Localization - Brazil Portuguese (Português Brasil) <pt-br.cfg>
#    description: progress toward Brazil Portuguese (Português Brasil) <pt-br.cfg> localization
#    state: open
#    
#  - title: Localization - Russian (Русский) <ru.cfg>
#    description: progress toward Russian (Русский) <ru.cfg> localization
#    state: open
#    
#  - title: Localization - Swedish (Svenska) <sw-sw.cfg>
#    description: progress toward Swedish (Svenska) <sw-sw.cfg> localization
#    state: open
#    
#  - title: Localization - Taiwanese (国语) <zh-tw.cfg>
#    description: progress toward Taiwanese (国语) <zh-tw.cfg> localization
#    state: open
#    
#  - title: Localization - Simplified Chinese (简体中文) <zh-cn.cfg>
#    description: progress toward Simplified Chinese (简体中文) <zh-cn.cfg> localization
#    state: open